# Custom Language File for Launcher Customizer

[ejs.app]
title = "Ordina Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/kevinfosse/SUSLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/aq3eND4Q"

[ejs.settings]
sourceGithubLink = "https://github.com/kevinfosse/SUSLauncher"
supportLink = "https://github.com/kevinfosse/SUSLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO ORDINA"
welcomeDescription = "Rejoins l'aventure"
welcomeDescCTA = "Suspect"
