# Custom Language File for Launcher Customizer

[ejs.app]
title = "Ordina Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/kevinfosse/Ordina-Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/aq3eND4Q"

[ejs.settings]
sourceGithubLink = "https://github.com/kevinfosse/Ordina-Launcher"
supportLink = "https://github.com/kevinfosse/Ordina-Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO ORDINA"
welcomeDescription = "Rejoins l'aventure magique sur"
welcomeDescCTA = "ORDINA"
